services:
  spottarr:
    container_name: spottarr
    hostname: spottarr
    build: 
      context: .
      dockerfile: ./src/Spottarr.Web/Dockerfile
    image: ghcr.io/spottarr/spottarr:latest
    environment:
      USENET__HOSTNAME: "my.news.server.com"
      USENET__USERNAME: ""
      # Make sure to escape special characters like $ and \n properly
      USENET__PASSWORD: ""
      USENET__PORT: "563"
      USENET__USETLS: "true"
      USENET__MAXCONNECTIONS: "10"
      SPOTNET__RETRIEVEAFTER: "2024-10-01T00:00:00Z"                     
    ports:
      - "8383:8080"
    volumes:
      - spottarr-data:/data
volumes:
  spottarr-data:
