name: Release image
on:
  release:
    types: [published]
jobs:
  release:
    name: Release docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #- name: Login to Docker Hub
      #  uses: docker/login-action@v3
      #  with:
      #    username: ${{ vars.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64 #,linux/arm64
          file: src/Spottarr.Web/Dockerfile
          push: true
          tags: |
            ${{ github.event.release.prerelease == false && 'ghcr.io/spottarr/spottarr:latest' || '' }}
            ghcr.io/spottarr/spottarr:${{ github.event.release.tag_name }}
